#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
#spring.datasource.username=shopli
#spring.datasource.password=shopli
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.show-sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring:
  datasource.username: shopli
  datasource.password: shopli
  datasource.url: jdbc:oracle:thin:@localhost:1521:orcl
  datasource.driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show_sql: true
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc.batch_size: 100
        connection.provider_disables_autocommit: false
        format_sql: true
        proc.param_null_passing: true
        query.in_clause_parameter_padding: true
        hibernate.dialect: org.hibernate.dialect.Oracle12cDialect
    hibernate:      
      ddl-auto: none
      use-new-id-generator-mappings: true
      format_sql: true
      show_sql: true
      package_to_scan: com.bezkoder.spring
      naming:        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  kafka:
    listener:
      ack-mode: manual
    bootstrap-servers: localhost:9092   
    consumer:
      enable-auto-commit: false
      bootstrap-servers: localhost:9092
      group-id: group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
           json:
             trusted:
               packages: vn.kafka.app.*
           deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
           deserializer.value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
